SystemBlog/DjangoExtSystem/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import static

from DjangoExtSystem import settings
from utils.upload_image import upload_image

from front import views
urlpatterns = [
    path(r'app/', include(('app.urls', 'app'), namespace='app')),
    path('', views.index),
    path(r'users/', include(('users.urls', 'users'), namespace='users')),
    path(r'front/', include(('front.urls', 'front'), namespace='front')),
    # kindeditor编辑器上传图片地址
    re_path(r'^util/upload/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
]

# 配置media访问路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SystemBlog/app/urls.py
from django.urls import path

from app import views

urlpatterns = [
    path(r'index/', views.index, name='index'),
]

SystemBlog/front/urls.py
from django.urls import path
from front import views

urlpatterns = [
    path('index/', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('infopic/<int:id>/', views.infopic, name='infopic'),
    path('list/', views.list, name='list'),
]

SystemBlog/users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    # 注册
    path('register/', views.register, name='register'),
    # 登录
    path('login/', views.login, name='login'),
    # 首页
    path('index/', views.index, name='index'),
    # 注销
    path('logout/', views.logout, name='logout'),
    # 编辑文章
    path('edit_article/<int:id>/', views.edit_article, name='edit_article'),
    # 文章列表
    path('article/', views.article, name='article'),
    path('category/', views.category, name='category'),
    path('add_article/', views.add_article, name='add_article'),
    path('del_article/<int:id>/', views.del_article, name='del_article'),
    path('add_category/', views.add_category, name='add_category'),
    path('del_category/<int:id>/', views.del_category, name='del_category'),
    path('edit_category/<int:id>/', views.edit_category, name='edit_category'),
    path('add_resueme/',views.add_resueme,name='add_resueme')
]

SystemBlog/templates/about_f.html
{% extends 'index_base_main.html' %}


{% block content %}
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">Lirocklei个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{% url 'front:index' %}">网站首页</a></li>
      <li><a href="" onclick="pic()">我的相册</a></li>
      <li><a href="{% url 'front:list' %}">文章列表</a></li>
      <li><a href="{% url 'front:about' %}">关于杨青，致敬</a></li>
      <li><a href="" onclick="ly()">留言</a></li>
      <li><a href="{% url 'users:index' %}">管理员后台</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">

    <div class="about_me">
      <h2>关于我</h2>
      <ul>
        <i><img src="/static/images/4.jpg"></i>
        <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
      </ul>
    </div>

    <div class="wdxc">
      <h2>我的相册</h2>
      <ul>
        <li><a href="/"><img src="/static/images/7.jpg"></a></li>
        <li><a href="/"><img src="/static/images/8.jpg"></a></li>
        <li><a href="/"><img src="/static/images/9.jpg"></a></li>
        <li><a href="/"><img src="/static/images/10.jpg"></a></li>
        <li><a href="/"><img src="/static/images/11.jpg"></a></li>
        <li><a href="/"><img src="/static/images/12.jpg"></a></li>
      </ul>
    </div>

    <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>

    <div class="fenlei">
      <h2>文章分类</h2>
      <ul>
          {% for result in results %}
        <li><a href="/">{{ result.0 }}（{{ result.1 }}）</a></li>
          {% endfor %}
      </ul>
    </div>

    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/images/weixin.jpg">
      </ul>
    </div>
  </aside>
  <main class="r_box">
     <div class="about">
      <p>杨青，女，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。我入行早，大家也亲切的叫我&ldquo;青姐&rdquo;。<br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
    <img src="/static/images/1.jpg">        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
    <img src="/static/images/1.jpg">        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
          <h2>About my blog</h2>
          <p>域 名：www.yangqq.com 创建于2011年01月12日&nbsp;</p>
          <br />
          <p>服务器：阿里云服务器&nbsp;&nbsp;<a href="https://promotion.aliyun.com/ntms/act/ambassador/sharetouser.html?userCode=8smrzoqa&amp;productCode=vm" target="_blank"><span style="color:#FF0000;"><strong>前往阿里云官网购买&gt;&gt;</strong></span></a></p>
          <br />
          <p>备案号：蜀ICP备11002373号-1</p>
          <br />
          <p>程 序：PHP 帝国CMS7.5</p>

     </div>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">Lirocklei个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
<script>
  function pic(){
    alert('相册不开放,刷新页面')
    location.reload
  }
   function ly(){
    alert('留言不开放,刷新页面')
    location.reload
  }

</script>

{% endblock %}

SystemBlog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
            <meta charset="utf-8">
        <meta name="renderer" content="webkit">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock %}

    {% block title %}
    {% endblock %}

    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
{% block content %}

{% endblock %}
</body>
</html>

SystemBlog/templates/base_main.html
{% extends 'base.html' %}

    {% block css %}
        <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="/static/css/style.css">
        <link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css">
        <link rel="apple-touch-icon-precomposed" href="/static/images/icon/icon.png">
        <link rel="shortcut icon" href="/static/images/icon/favicon.ico">
        <link rel="stylesheet" type="text/css" href="/static/css/login.css">
    {% endblock %}


    {% block js %}
        <script src="/static/js/jquery-2.1.4.min.js"></script>
    {% endblock %}

SystemBlog/templates/edit.html
{% extends 'base.html' %}



{% block js %}
    {% load static %}
    <script type="text/javascript" src="{% static 'kindeditor/kindeditor-all.js' %}"></script>
    <script type="text/javascript" src="{% static 'kindeditor/lang/zh-CN.js' %}"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id',{
                    uploadJson:'/util/upload/kindeditor'
                });
        });
    </script>
    {{ block.super }}
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        标题：<input type="text" name="title" value="{{ result.0 }}">
        <p>当前栏目：{{ result.1 }}，请重新选择</p>
        <ul class="category-list">
                  {% for cat in aaa %}
                  <li>
                    <label>

                      <input {% if result.4 == cat.id %} checked {% endif %}  name="category" type="radio" value="{{cat.id}}">

                       <em class="hidden-md">( {{forloop.counter}}: <span>{{cat.category}}</span> )</em></label>
                  </li>
                  {% endfor %}
        </ul>

        关键字：<input type="text" name="keywords" value="{{ result.2 }}">
        内容：<textarea id="editor_id" name="content">{{ result.3 }}</textarea>
        <p><input type="submit" value="提交"></p>
    </form>
    <p><a href="{% url 'users:index' %}">返回首页</a></p>
    <p><a href="{% url 'users:article' %}">查看文章</a></p>
    <p><a href="{% url 'users:category' %}">查看栏目</a></p>
{% endblock %}

SystemBlog/templates/index.html
{% extends 'base_main.html' %}

{% block title %}
异清轩博客管理系统
{% endblock %}




  {% block content %}
<section class="container-fluid">
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">YlsatCMS</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="">消息 <span class="badge">无</span></a></li>
            <li class="dropdown"> <a href="{% url 'users:add_resueme' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Lirocklei个人信息<span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a title="查看或修改个人信息" data-toggle="modal" data-target="#seeUserInfo">个人信息</a></li>
                <li><a title="查看您的登录记录" data-toggle="modal" data-target="#seeUserLoginlog">登录记录</a></li>
              </ul>
            </li>
            <li><a href="{% url 'users:logout' %}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
            <li><a href="{% url 'front:index' %}" data-toggle="modal" data-target="#WeChat">返回前端文章</a></li>
          </ul>
          <form action="" method="" class="navbar-form navbar-right" role="search">
            <div class="input-group">
              <input type="text" class="form-control" autocomplete="off" placeholder="暂不开放" maxlength="15">
              <span class="input-group-btn">
              <button class="btn btn-default" type="button">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
    </nav>
  </header>

  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="active"><a href="index.html"></a></li>

      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'users:index'  %}">首页</a></li></ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'users:article'  %}">文章</a></li></ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'users:category'  %}">栏目</a></li>
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href=""></a></li>
      </ul>
    </aside>


      <h1 class="page-header"> </h1>
      <h1 class="page-header">&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&ensp;&emsp;&emsp;欢迎Lirocklei登陆首页</h1>
    <h1 class="page-header"> </h1>
      <h1 class="page-header">&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;系统信息</h1>
      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead>
            <tr> </tr>
          </thead>
          <tbody>
            <tr>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;管理员:</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Lirocklei</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;服务器软件:</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Apache/2.4.10 (Win32) OpenSSL/1.0.1i mod_fcgid/2.3.9</td>
            </tr>
            <tr>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;浏览器:</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Chrome47</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;PHP版本:</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;5.6.1</td>
            </tr>
            <tr>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;操作系统:</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;Windows 10</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;PHP运行方式:</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;CGI-FCGI</td>
            </tr>
            <tr>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;登录者IP:</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;::1:55570</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;MYSQL版本:</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;5.5.40</td>
            </tr>
            <tr>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;程序版本:</td>
              <td class="version">&emsp;&emsp;&emsp;YlsatCMS 1.0 <font size="-6" color="#BBB">(20160108160215)</font></td>
              <td>上传文件:</td>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;可以 <font size="-6" color="#BBB">(最大文件：2M ，表单：8M )</font></td>
            </tr>
            <tr>
              <td>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;程序编码:</td>
              <td>UTF-8</td>
              <td>当前时间:</td>
              <td>2016-01-08 15:50:30</td>
            </tr>
          </tbody>
          <tfoot>
            <tr></tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</section>

    {% endblock %}

SystemBlog/templates/index_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head%}
    {% endblock %}

    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

SystemBlog/templates/index_f.html
{% extends 'index_base_main.html' %}

{% block content %}
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">Lirocklei个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{% url 'front:index' %}">网站首页</a></li>
      <li><a href="" onclick="pic()">我的相册</a></li>
      <li><a href="{% url 'front:list' %}">文章列表</a></li>
      <li><a href="{% url 'front:about' %}">关于杨青，致敬</a></li>
      <li><a href="" onclick="ly()">留言</a></li>
      <li><a href="{% url 'users:index' %}">管理员后台</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
      <div class="about_me">
        <h2>关于我</h2>
        <ul>
          <i><img src="/static/images/20181221111918.jpg"></i>
          <p><b>{{ resume.username }}</b>，{{ resume.resume }}</p>
        </ul>
      </div>
      <div class="wdxc">
        <h2>我的相册,仅供欣赏</h2>
        <ul>
          <li><a href="/"><img src="/static/images/7.jpg"></a></li>
          <li><a href="/"><img src="/static/images/8.jpg"></a></li>
          <li><a href="/"><img src="/static/images/9.jpg"></a></li>
          <li><a href="/"><img src="/static/images/10.jpg"></a></li>
          <li><a href="/"><img src="/static/images/11.jpg"></a></li>
          <li><a href="/"><img src="/static/images/12.jpg"></a></li>
        </ul>
      </div>
      <div class="search">
        <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>

      <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
          {% for result in results %}
          <li><a >{{ result.0 }}（{{ result.1 }}）</a></li>
          {% endfor %}
        </ul>
      </div>

      <div class="tuijian">

        <h2>站长推荐</h2>
        <ul>
          <li><a href="{% url 'front:infopic' first.id %}">{{ first.title }}</a></li>
        </ul>
      </div>

      <div class="links">
        <h2>友情链接</h2>
        <ul>
          <a href="https://lirocklei.github.io/">{{ resume.username }}个人博客</a> <a href="https://www.jianshu.com/">{{ resume.username }}简书简书</a>
        </ul>
      </div>
      <div class="guanzhu">
        <h2>关注我 么么哒</h2>
        <ul>
          <img src="/static/images/weixin.jpg">
        </ul>
      </div>
  </aside>
  <main class="r_box">

    {% for article in articles %}
    <li><i><a href="{% url 'front:infopic' article.id %}"><img src="/static/images/1.jpg"></a></i>
      <h3><a href="{% url 'front:infopic' article.id %}">{{ article.title }}</a></h3>
      <p><a href="{% url 'front:infopic' article.id %}">{{ article.content }}</a></p>
    </li>
    {% endfor %}


    当前{{ articles.number }}页，共{{ articles.paginator.num_pages }}页

        {% if articles.has_previous %}
            <a class="allpage" href="{% url 'front:index' %}?page={{ articles.previous_page_number }}">上一页</a>
        {% endif %}
        {% for i in articles.paginator.page_range %}
            <!--<a href="/app/all_stu/?page={{ i }}">{{ i }}</a>-->
            <a  class="allpage" href="{% url 'front:index' %}?page={{ i }}">{{ i }}</a>
        {% endfor %}
        {% if articles.has_next %}
            <a class="allpage" href="{% url 'front:index' %}?page={{ articles.next_page_number }}">下一页</a>
        {% endif %}

  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">Lirocklei个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
<script>
  function pic(){
    alert('相册不开放,刷新页面')
    location.reload
  }
   function ly(){
    alert('留言不开放,刷新页面')
    location.reload
  }

</script>
{% endblock %}

SystemBlog/templates/list_f.html
{% extends 'index_base_main.html' %}


{% block content %}
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">Lirocklei个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{% url 'front:index' %}">网站首页</a></li>
      <li><a href="" onclick="pic()">我的相册</a></li>
      <li><a href="{% url 'front:list' %}">文章列表</a></li>
      <li><a href="{% url 'front:about' %}">关于杨青，致敬</a></li>
      <li><a href="" onclick="ly()">留言</a></li>
      <li><a href="{% url 'users:index' %}">管理员后台</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
 <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
      <h2>文章分类</h2>

        <ul>
          {% for result in results %}
          <li><a href="/">{{ result.0 }}（{{ result.1 }}）</a></li>
          {% endfor %}
        </ul>

    </div>
    <div class="tuijian">
      <h2>站长推荐</h2>

        <ul>
          <li><a href="{% url 'front:infopic' first.id %}">{{ first.title }}</a></li>
        </ul>

    </div>
     <div class="tuijian">
      <h2>点击排行</h2>

        <ul>
          <li><a href="{% url 'front:infopic' first.id %}">{{ first.title }}</a></li>
        </ul>

    </div>
<div class="cloud">
      <h2>标签云</h2>
      <ul>
        {% for article in articles1 %}
            <a href="/">{{ article.key_words }}</a>
        {% endfor %}
      </ul>
    </div>
    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/images/weixin.jpg">
      </ul>
    </div>
  </aside>
  <main class="r_box">

    {% for article in articles %}
    <li><i><a href="{% url 'front:infopic' article.id %}"><img src="/static/images/3.jpg"></a></i>
      <h3><a href="{% url 'front:infopic' article.id %}">{{ article.title }}</a></h3>
      <p><a href="{% url 'front:infopic' article.id %}">{{ article.content }}</a></p>
    </li>
    {% endfor %}

        当前{{ articles.number }}页，共{{ articles.paginator.num_pages }}页

        {% if articles.has_previous %}
            <a class="allpage" href="{% url 'front:index' %}?page={{ articles.previous_page_number }}">上一页</a>
        {% endif %}
        {% for i in articles.paginator.page_range %}
            <!--<a href="/app/all_stu/?page={{ i }}">{{ i }}</a>-->
            <a  class="allpage" href="{% url 'front:index' %}?page={{ i }}">{{ i }}</a>
        {% endfor %}
        {% if articles.has_next %}
            <a class="allpage" href="{% url 'front:index' %}?page={{ articles.next_page_number }}">下一页</a>
        {% endif %}


    <div class="pagelist">
    {% if articles.has_previous %}
        <a class="allpage" href="{% url 'front:index' %}?page={{ articles.previous_page_number }}"><b>上一页</b></a>
    {% endif %}

     {% for i in articles.paginator.page_range %}
            <a  class="allpage" href="{% url 'front:index' %}?page={{ i }}">{{ i }}</a>
     {% endfor %}

      {% if articles.has_next %}
            <a class="allpage" href="{% url 'front:index' %}?page={{ articles.next_page_number }}">下一页</a>
       {% endif %}

    </div>
  </main>
</article>
<footer>
  <p>Design by <a href="https://lirocklei.github.io/" target="_blank">{{ resume.username }}个人博客</a> <a href="/">蜀ICP备110XXXXX</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
<script>
  function pic(){
    alert('相册不开放,刷新页面')
    location.reload
  }
   function ly(){
    alert('留言不开放,刷新页面')
    location.reload
  }

</script>
{% endblock %}